version: '3.8'
services:
  fritzbox-callmonitor:
    image: california444/fritzbox-callmonitor:latest
    container_name: fritzbox-callmonitor
    # env_file:
    #   - .env
    environment:
      # Alternativ zu .env k√∂nnen die Variablen hier gesetzt werden:
      FRITZBOX_IP: "192.168.0.1"
      TELEGRAM_BOT_TOKEN: "DEIN_BOT_TOKEN_HIER"
      TELEGRAM_CHAT_ID: "DEINE_CHAT_ID_HIER"
    restart: always
    privileged: true
    tty: true
    stdin_open: true
