version: '3.8'
services:
  fritzbox-callmonitor:
    build: .
    container_name: fritzbox-callmonitor
    # env_file:
      #. - .env
    environment:
      # Alternativ zu .env können die Variablen hier gesetzt werden:
      FRITZBOX_IP: "192.168.0.1"
      TELEGRAM_BOT_TOKEN: "DEIN_BOT_TOKEN_HIER"
      TELEGRAM_CHAT_ID: "DEINE_CHAT_ID_HIER"
    restart: always
    privileged: true
    # systemd benötigt diese Flags
    tty: true
    stdin_open: true
    # Ports müssen nicht veröffentlicht werden, da der Callmonitor die Fritzbox aktiv kontaktiert
